apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
  namespace: {{ .Values.nginx.namespace }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.nginx.strategy.maxSurge }}
      maxUnavailable: {{ .Values.nginx.strategy.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
        name: nginx-app
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: {{ .Values.nginx.resources.limits.cpu }}
            memory: {{ .Values.nginx.resources.limits.memory }}
          requests:
            cpu: {{ .Values.nginx.resources.requests.cpu }}
            memory: {{ .Values.nginx.resources.requests.memory }}
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
