apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apache.name }}
  namespace: {{ .Values.apache.namespace }}
spec:
  replicas: {{ .Values.apache.replicaCount }}
  selector:
    matchLabels:
      app: apache-app
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.apache.strategy.maxSurge }}
      maxUnavailable: {{ .Values.apache.strategy.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache-app
    spec:
      containers:
      - image: {{ .Values.apache.image.repository }}:{{ .Values.apache.image.tag }}
        name: apache-app
        imagePullPolicy: {{ .Values.apache.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: {{ .Values.apache.resources.limits.cpu }}
            memory: {{ .Values.apache.resources.limits.memory }}
          requests:
            cpu: {{ .Values.apache.resources.requests.cpu }}
            memory: {{ .Values.apache.resources.requests.memory }}
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
