apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nginx.secret_nginx_website_config.name }}
stringData:
  web.conf: |
    {{ .Files.Get .Values.nginx.secret_nginx_website_config.path | quote }}