apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: app
  labels:
    app: test-pod
spec:
  containers:
    - name: test-pod-0
      image: busybox
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
