apiVersion: v1
kind: Pod
metadata:
  name: test_pod
  labels:
    app: test_pod
spec:
  containers:
    - name: test_pod
      image: busybox
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
