apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: {{ .Values.nginx.namespace }}
spec:
  selector:
    app: apache-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP